# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19YOB4IgWPsWlQ8ExMPm39CG8aur5jT-n
"""

import random

operators = ["+", "-", "*"]
min_operand = 10
max_operand = 100

def generate_problem():
    left = random.randint(min_operand, max_operand)
    right = random.randint(min_operand, max_operand)
    op = random.choice(operators)

    expr = str(left) + " " + op + " " + str(right)
    answer = eval(expr)
    return expr, answer

for i in range(10):
    expr, answer = generate_problem()
    while True:
        guess = int(input("problem #" + str(i + 1) + ": " + expr + " = "))
        if guess == answer:
            print("Correct!")
            break
        else:
            print("Incorrect. Try again.")